// This file is generated by running `npm run download-configuration-from-google-sheets`
/* eslint-disable */

module.exports = [
	{
		"domain": "ab-com",
		"tld": "cz",
		"origin": "https://www.ab-com.cz/",
		"exampleProductPath": "apple-ipad-9-7-2018-wi-fi-128gb-gold/"
	},
	{
		"domain": "alfa",
		"tld": "cz",
		"origin": "https://www.alfa.cz/",
		"exampleProductPath": "product.php?eid=105160006000000509O"
	},
	{
		"domain": "czc",
		"tld": "cz",
		"origin": "https://www.czc.cz/",
		"exampleProductPath": "apple-iphone-11-64gb-black/269718/produkt"
	},
	{
		"domain": "datart",
		"tld": "cz,sk",
		"origin": "https://www.datart.cz/",
		"exampleProductPath": "iphone-11-64gb-black-mwlt2cn-a.html"
	},
	{
		"domain": "electroworld",
		"tld": "cz",
		"origin": "https://www.electroworld.cz/",
		"exampleProductPath": "apple-iphone-11-64-gb-cerny"
	},
	{
		"domain": "kasa",
		"tld": "cz",
		"origin": "https://www.kasa.cz/",
		"exampleProductPath": "mobilni-telefon-apple-iphone-11-64-gb-black-mwlt2cn-a/"
	},
	{
		"domain": "lekarna",
		"tld": "cz",
		"origin": "https://www.lekarna.cz/",
		"exampleProductPath": "ibalgin-rapidcaps-400mg-cps.mol.20/"
	},
	{
		"domain": "mall",
		"tld": "cz,sk",
		"origin": "https://www.mall.cz/",
		"exampleProductPath": "mobilni-telefony/apple-iphone-11-64gb-black"
	},
	{
		"domain": "mironet",
		"tld": "cz",
		"origin": "https://www.mironet.cz/",
		"exampleProductPath": "apple-iphone-11-64gb-cerna-61quot-hexacore-4gb-64gb-12mp12mp12mp-ios13+dp409453/"
	},
	{
		"domain": "mountfield",
		"tld": "cz,sk",
		"origin": "https://www.mountfield.cz/",
		"exampleProductPath": "sekera-patriot-l-73-cm/1900-g-1zst4100"
	},
	{
		"domain": "tsbohemia",
		"tld": "cz",
		"origin": "https://www.tsbohemia.cz/",
		"exampleProductPath": "apple-iphone-11-64gb-purple-mwlx2cn-a-_d333467.html"
	}
]
