name: CI
on: [push]
jobs:
  deploy:
    if: github.ref == 'refs/heads/master' && startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build:chrome
      - run: npm run publish:chrome
        env:
          EXTENSION_ID: "jmhkgcmmgjblnkjkbgjggkaeifacakgi"
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
